Import( [ 'env_test' ] )

env_test.Append( CPPPATH = '..' )
env_test.Append( LIBS = 'gmbus-1.0' )
env_test.Append( LINKFLAGS = [ '-L./gmbus' ] )

sources = ( 'crypt.c', 'fredtest.c', 'mbustest.c', 'mentity.c', 'mtest.c',
			 'printll.c', 'rpcclient.c', 'rpcserver.c' )
programs = []
for source in sources:
	programs.append( env_test.Program( source[ : -2 ], [ source ] ) )

Return( 'programs' )
